### ISSUE TITLE
ERROR "Deprecation Listener added for a synchronous 'DOMNodeInserted'"

### ISSUE THREAD

**Issue by gjtorbett** [wiris/moodle-qtype_shortanswerwiris#50]
Hello, I am with a new installation of Moodle 4.3 and PHP 8.2.
When trying to add a question from the Wiris Quizzes package. I get the following error in the console.

[Deprecation]Listener added for a synchronous 'DOMNodeInserted' DOM Mutation Event. This event type is deprecated (<URL>) and work is underway to remove it from this browser. Usage of this event listener will cause performance issues today, and represents a risk of future incompatibility. Consider using MutationObserver instead.

It seems to come from the WIRIS service itself.

![image](https://github.com/wiris/moodle-qtype_shortanswerwiris/assets/59968952/7db980d5-09c0-43bd-b3ee-5e25bbb39525)

I would greatly appreciate your help

**Comment by ptorrent-at-wiris** [comment]
Hi Guillermo,
thanks for bringing this to our attention. We are going to release a version replacing the deprecated component in the coming weeks. We will keep you updated once we release it.

Best,

**Comment by gjtorbett** [comment]
Thank you very much for your response, I will be attentive

**Comment by ptorrent-at-wiris** [comment]
Dear @gjtorbett , today we released version 4.11.2 which should fix the issue you reported. Therefore I close the issue. Thanks!

**Comment by gjtorbett** [comment]
Thank you very much for letting me know, I'll put it to the test. Greetings.
